spring:
    application:
        name: sample-app
    profiles.active: dev

server:
    forward-headers-strategy: framework
    port: 8888

sample-config:
    property: "value"

management:
    endpoint:
        refresh:
            enabled: true
        shutdown:
            enabled: true
    endpoints.web.exposure.include: '*'
